language: generic

# The dotfiles directory should be in a specific place
before_install:
  - mv -f $TRAVIS_BUILD_DIR $HOME/dotfiles
  - cd $HOME/dotfiles

install:
  # For some reason, Travis has an issue with asking for sudo while the script is running,
  # so we're `sudo`ing before it'll run to update the timestamp (`sudo -v` does not work either)
  - sudo echo
  - ./install.sh -y

matrix:
  include:

    - os: osx
      before_script:
        - brew install shellcheck

    - os: linux
      dist: trusty
      before_script:
        - sudo apt-get update -qqy
        - sudo apt-get install -qqy shellcheck

script:
  - ./_test/shellcheck.sh

sudo: required
