language: generic

env:
  - DEBUG_LOG_PATH=/tmp/dotfiles.debug.log

# The dotfiles directory should be in a specific place
before_install:
  - mv -f $TRAVIS_BUILD_DIR $HOME/dotfiles
  - cd $HOME/dotfiles

script:
  - ./install.sh -y --debug-log
  - cat $DEBUG_LOG_PATH
  - ./.test/shellcheck.sh

matrix:
  include:

    - os: osx
      sudo: false
      before_script:
        - brew install shellcheck

    - os: linux
      dist: bionic
      before_script:
        - sudo apt-get update -qqy
        - sudo apt-get install -qqy shellcheck
