language: generic

env:
  - DEBUG_LOG_PATH=/tmp/dotfiles.debug.log

# The dotfiles directory should be in a specific place
before_install:
  - mv -f $TRAVIS_BUILD_DIR $HOME/dotfiles
  - cd $HOME/dotfiles

install:
  - ./install.sh -y --debug-log
  - cat $DEBUG_LOG_PATH

matrix:
  include:

    - os: osx
      sudo: false
      before_install:
        - brew install shellcheck

    - os: linux
      dist: trusty
      before_install:
        - sudo apt-get update -qqy
        - sudo apt-get install -qqy shellcheck coreutils

script:
  - ./.test/shellcheck.sh

sudo: required
